// src/App.vue
<script setup lang="tsx">
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import type { SplitterPanel } from "reka-ui";
import { reactive, ref } from "vue";
import test_data from "../testing/artifacts_data.json";
import ArtifactsList from "./components/ArtifactsList.vue";
import ClearFilterButton from "./components/ClearFilterButton.vue";
import FilterGroup from "./components/FilterGroup.vue";
import {
  type ActiveFilters,
  type FilterInputs,
} from "./filtering/filterConfig";
import {
  elements,
  SK1_NAMES,
  SK2_NAMES,
  SK3_NAMES,
  weapons,
  type Artifacts,
  type Element,
  type RawArtifact,
  type Weapon
} from "./types";
import { getImage, updateSet } from "./utils";

const sidePanelRef = ref<InstanceType<typeof SplitterPanel>>();
const filters = reactive<ActiveFilters>({
  search: "",
  sk1Search: new Set<string>(),
  sk2Search: new Set<string>(),
  sk3Search: new Set<string>(),
  element: new Set<Element>(),
  weapon: new Set<Weapon>(),
});

export type FilterHandlers = {
  [K in keyof FilterInputs]: (value: FilterInputs[K]) => void;
};

const filterHandlers: FilterHandlers = {
  search: (value) => {
    filters.search = value;
  },
  sk1Search: (value) => {
    if (filters.sk1Search.has(value)) {
      filters.sk1Search = updateSet(filters.sk1Search, (s) => s.delete(value));
    } else {
      filters.sk1Search = updateSet(filters.sk1Search, (s) => s.add(value));
    }
  },
  sk2Search: (value) => {
    if (filters.sk2Search.has(value)) {
      filters.sk2Search = updateSet(filters.sk2Search, (s) => s.delete(value));
    } else {
      filters.sk2Search = updateSet(filters.sk2Search, (s) => s.add(value));
    }
  },
  sk3Search: (value) => {
    if (filters.sk3Search.has(value)) {
      filters.sk3Search = updateSet(filters.sk3Search, (s) => s.delete(value));
    } else {
      filters.sk3Search = updateSet(filters.sk3Search, (s) => s.add(value));
    }
  },
  element: (value) => {
    if (filters.element.has(value)) {
      filters.element = updateSet(filters.element, (s) => s.delete(value));
    } else {
      filters.element = updateSet(filters.element, (s) => s.add(value));
    }
  },
  weapon: (value) => {
    if (filters.weapon.has(value)) {
      filters.weapon = updateSet(filters.weapon, (s) => s.delete(value));
    } else {
      filters.weapon = updateSet(filters.weapon, (s) => s.add(value));
    }
  },
};

function filterUpdaterFactory<K extends keyof ActiveFilters>(key: K) {
  return (value: FilterInputs[K]) => {
    filterHandlers[key](value);
  };
}

function clearFilter<K extends keyof ActiveFilters | "all">(key: K) {
  switch (key) {
    case "all":
      filters.search = "";
      filters.sk1Search = new Set<string>();
      filters.sk2Search = new Set<string>();
      filters.sk3Search = new Set<string>();
      filters.element = new Set<Element>();
      filters.weapon = new Set<Weapon>();
      break;
    case "search":
      filters.search = "";
      break;
    case "sk1Search":
      filters.sk1Search = new Set<string>();
      break;
    case "sk2Search":
      filters.sk2Search = new Set<string>();
      break;
    case "sk3Search":
      filters.sk3Search = new Set<string>();
      break;
    case "element":
      filters.element = new Set<Element>();
      break;
    case "weapon":
      filters.weapon = new Set<Weapon>();
      break;
  }
}

const __SIDEBAR = {
  collapsedSize: 4,
  minSize: 20,
  defaultSize: 35,
};

// TODO: Remove for prod
// const rawData:RawArtifactData = JSON.parse(test_data)
// console.log(test_data)
const artifactsJSON: Record<string, RawArtifact> = Object.fromEntries(
  Object.entries(test_data).map(([id, artifactStr]) => [
    id,
    JSON.parse(artifactStr),
  ]),
);
const artifacts: Artifacts = {};
    Object.entries(artifactsJSON).forEach(([id, artifact]) => {

        artifacts[id] = {
            element: artifact.element as Element,
            weapon: artifact.weapon_group as Weapon,
            is_scrap: artifact.is_scrap,
            s1: {
                id: Math.floor(artifact.s1.skill_id / 10),
                name: artifact.s1.name,
                value: artifact.s1.effect_value,
                quality: artifact.s1.skill_quality
            },
            s2: {
                id: Math.floor(artifact.s2.skill_id / 10),
                name: artifact.s2.name,
                value: artifact.s2.effect_value,
                quality: artifact.s2.skill_quality
            },
            s3: {
                id: Math.floor(artifact.s3.skill_id / 10),
                name: artifact.s3.name,
                value: artifact.s3.effect_value,
                quality: artifact.s3.skill_quality
            },
            s4: {
                id: Math.floor(artifact.s4.skill_id / 10),
                name: artifact.s4.name,
                value: artifact.s4.effect_value,
                quality: artifact.s4.skill_quality
            },
        }
    })
</script>

<template>
  <div id="app" class="h-screen">
    <ResizablePanelGroup direction="horizontal">
      <ResizablePanel
        ref="sidePanelRef"
        collapsible
        :collapsed-size="__SIDEBAR.collapsedSize"
        :min-size="__SIDEBAR.minSize"
        :default-size="__SIDEBAR.defaultSize"
        class="bg-base-300 p-2"
      >
        <div class="w-full h-full overflow-auto">
          <!-- Show sidebar button -->
          <button
            class="btn btn-square btn-ghost bg-base-100 w-[30px] h-[30px] hover:bg-neutral-500"
            v-if="sidePanelRef?.isCollapsed"
            @click="
              sidePanelRef?.isCollapsed
                ? sidePanelRef?.expand()
                : sidePanelRef?.collapse()
            "
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              class="inline-block h-6 w-6 stroke-current"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="1"
                d="M4 6 h16 M4 12 h16 M4 18 h16"
              ></path>
            </svg>
          </button>

          <div class="flex flex-col items-center gap-2 pr-6">
            <div
              class="flex flex-col items-center gap-2"
              v-if="!sidePanelRef?.isCollapsed"
            >
              <!-- Clear Filters button -->
              <div class="flex items-center justify-center">
                <button
                  class="btn bg-base-100 hover:bg-red-400 h-7"
                  @click="clearFilter('all')"
                >
                  Clear All Filters
                </button>
              </div>

              <!-- Search bar -->
              <label class="input">
                <input
                  v-model="filters.search"
                  type="search"
                  placeholder="Search"
                />
              </label>

              <!-- Elements filter -->
              <div class="flex gap-2">
                <div class="flex items-center gap-2 h-[50px] overflow-auto">
                  <button
                    v-for="element in elements"
                    :key="element"
                    class="flex-none p-0.5 hover:bg-neutral-500 hover:cursor-pointer rounded-md"
                    :class="{ 'bg-accent': filters['element'].has(element) }"
                  >
                    <img
                      class="w-[30px] h-[30px]"
                      :src="getImage(`Icon_Element_${element}.png`)"
                      @click="filterUpdaterFactory('element')(element)"
                    />
                  </button>

                  <div class="flex items-center">
                    <ClearFilterButton @clear-filter="clearFilter('element')" />
                  </div>
                </div>
              </div>

              <!-- Weapons filter -->
              <div class="flex gap-2">
                <div class="flex overflow-auto">
                  <div
                    class="flex-none grid grid-flow-row grid-rows-2 grid-cols-5 overflow-auto pb-2"
                  >
                    <button
                      v-for="weapon in weapons"
                      :key="weapon"
                      class="p-0.5 hover:bg-neutral-500 hover:cursor-pointer rounded-md"
                      :class="{ 'bg-accent': filters['weapon'].has(weapon) }"
                    >
                      <img
                        class="h-[20px]"
                        :src="getImage(`Label_Weapon_${weapon}.png`)"
                        @click="filterUpdaterFactory('weapon')(weapon)"
                      />
                    </button>
                  </div>
                </div>
                <div class="flex items-center pb-2">
                  <ClearFilterButton @clear-filter="clearFilter('weapon')" />
                </div>
              </div>

              <!-- Skill Group 1 Filters -->
              <FilterGroup
                :btn-names="SK1_NAMES"
                group-name="Skill Group 1 Search"
                :current-filters="filters['sk1Search']"
                :selected-skills-updater="filterUpdaterFactory('sk1Search')"
                @clear-filter="clearFilter('sk1Search')"
              />

              <!-- Skill Group 2 Filters -->
              <FilterGroup
                :btn-names="SK2_NAMES"
                group-name="Skill Group 2 Search"
                :current-filters="filters['sk2Search']"
                :selected-skills-updater="filterUpdaterFactory('sk2Search')"
                @clear-filter="clearFilter('sk2Search')"
              />

              <!-- Skill Group 3 Filters -->
              <FilterGroup
                :btn-names="SK3_NAMES"
                group-name="Skill Group 3 Search"
                :current-filters="filters['sk3Search']"
                :selected-skills-updater="filterUpdaterFactory('sk3Search')"
                @clear-filter="clearFilter('sk3Search')"
              />
            </div>
          </div>
        </div>
      </ResizablePanel>
      <ResizableHandle />
      <ResizablePanel class="bg-base-300">
        <div class="w-full h-full overflow-auto">
          <ArtifactsList :artifacts="artifacts" :filter-opts="filters"/>
        </div>
      </ResizablePanel>
    </ResizablePanelGroup>
  </div>
</template>

// app/page.tsx
'use client'

import { useState } from "react"
import { Group, Panel, Separator, usePanelCallbackRef } from "react-resizable-panels"
import ArtifactsList from "./components/ArtifactsList"
import ClearFilterButton from "./components/ClearFilterButton"
import FilterGroup from "./components/FilterGroup"
import { ActiveFilters, FilterInputs } from "./filtering/filterConfig"
import type { Artifacts, Element, Weapon } from "./types"
import { elements, SK1_NAMES, SK2_NAMES, SK3_NAMES, weapons } from "./types"

const __default_filter: ActiveFilters = {
    search: "",
    sk1Search: new Set<string>,
    sk2Search: new Set<string>,
    sk3Search: new Set<string>,
    element: new Set<Element>,
    weapon: new Set<Weapon>

}

export type FilterHandlers = {
    [K in keyof FilterInputs]: (value: FilterInputs[K]) => void;
}

const __SIDEBAR = {
    collapsedSize: 40,
    minSize: 100,
    defaultSize: "35%"
}

export default function ViewerHome() {
    // const { artifactsJSON } = useArtifactsJSON();
    const [filters, setFilters] = useState<ActiveFilters>(__default_filter);
    const [rr, toggleReRender] = useState(false);
    const [sidebarIsShown, setShowSidebar] = useState(false);
    const [sidebarPanelRef, setSidebarPanelRef] = usePanelCallbackRef();
    
    const filterHandlers: FilterHandlers = {
        search: (value) => {
            setFilters(prev => ({ ...prev, ["search"]: value }))
        },
        sk1Search: (value) => {
            if (filters["sk1Search"].has(value)) {
                filters["sk1Search"].delete(value)
            } else {
                filters["sk1Search"].add(value)
            }
            toggleReRender(!rr);
        },
        sk2Search: (value) => {
            if (filters["sk2Search"].has(value)) {
                filters["sk2Search"].delete(value)
            } else {
                filters["sk2Search"].add(value)
            }
            toggleReRender(!rr);
        },
        sk3Search: (value) => {
            if (filters["sk3Search"].has(value)) {
                filters["sk3Search"].delete(value)
            } else {
                filters["sk3Search"].add(value)
            }
            toggleReRender(!rr);
        },
        element: (value) => {
            const castedValue = value as Element;
            if (filters["element"].has(castedValue)) {
                filters["element"].delete(castedValue)
            } else {
                filters["element"].add(castedValue)
            }
            toggleReRender(!rr);
        },
        weapon: (value) => {
            const castedValue = value as Weapon;
            if (filters["weapon"].has(castedValue)) {
                filters["weapon"].delete(castedValue)
            } else {
                filters["weapon"].add(castedValue)
            }
            toggleReRender(!rr);
        }
    }

    function filterUpdater<K extends keyof ActiveFilters>(key: K) {
        return (value: FilterInputs[K]) => {
            filterHandlers[key](value);
        };
    }

    function filterClearer<K extends keyof ActiveFilters>(key: K) {
        switch (key) {
            case "search":
                return () => setFilters(prev => ({ ...prev, [key]: "" }));
            case "sk1Search":
                return () => setFilters(prev => ({ ...prev, [key]: new Set<string> }));;
            case "sk2Search":
                return () => setFilters(prev => ({ ...prev, [key]: new Set<string> }));;
            case "sk3Search":
                return () => setFilters(prev => ({ ...prev, [key]: new Set<string> }));;
            case "element":
                return () => setFilters(prev => ({ ...prev, [key]: new Set<Element> }));;
            case "weapon":
                return () => setFilters(prev => ({ ...prev, [key]: new Set<Weapon> }));;
        }
    }

    const showSidebar = () => {
        setShowSidebar(true)
        sidebarPanelRef?.resize(__SIDEBAR.defaultSize)
    }

    const onPanelResize = () => {
        if (sidebarPanelRef?.isCollapsed()) {
            setShowSidebar(false)
        } else {
            setShowSidebar(true)
        }
    }

    if (!artifactsJSON) {
        return <p className="text-red-500 mt-2">Loading...or json data not found.</p>
    }

    const artifacts: Artifacts = {};
    Object.entries(artifactsJSON).forEach(([id, artifact]) => {
        // const info = JSON.parse(v);

        artifacts[id] = {
            element: artifact.element as Element,
            weapon: artifact.weapon_group as Weapon,
            is_scrap: artifact.is_scrap,
            s1: {
                id: Math.floor(artifact.s1.skill_id / 10),
                name: artifact.s1.name,
                value: artifact.s1.effect_value,
                quality: artifact.s1.skill_quality
            },
            s2: {
                id: Math.floor(artifact.s2.skill_id / 10),
                name: artifact.s2.name,
                value: artifact.s2.effect_value,
                quality: artifact.s2.skill_quality
            },
            s3: {
                id: Math.floor(artifact.s3.skill_id / 10),
                name: artifact.s3.name,
                value: artifact.s3.effect_value,
                quality: artifact.s3.skill_quality
            },
            s4: {
                id: Math.floor(artifact.s4.skill_id / 10),
                name: artifact.s4.name,
                value: artifact.s4.effect_value,
                quality: artifact.s4.skill_quality
            },
        }
    })

    return (
        <div className="h-screen">
            <Group>
                <Panel collapsible collapsedSize={__SIDEBAR.collapsedSize} minSize={__SIDEBAR.minSize} defaultSize={__SIDEBAR.defaultSize} className="bg-base-300 p-2" panelRef={setSidebarPanelRef} onResize={onPanelResize}>
                    {/* Show sidebar button */}
                    <button className={`btn btn-square btn-ghost bg-base-100 w-[30px] h-[30px] hover:bg-neutral-500 ${sidebarIsShown ? "hidden" : ""}`} onClick={showSidebar}>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            className="inline-block h-6 w-6 stroke-current"
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth="1"
                                d="M4 6 h16 M4 12 h16 M4 18 h16"
                            ></path>
                        </svg>
                    </button>
                    <div className="flex flex-col items-center gap-2 pr-6">
                        <div className={`flex flex-col items-center gap-2 ${!sidebarIsShown ? "hidden" : ""}`}>
                            {/* Clear Filters button */}
                            <div className={`flex items-center justify-center `}>
                                <button className="btn bg-base-100 hover:bg-red-400 h-7" onClick={() => setFilters(__default_filter)}> Clear Filters </button>
                            </div>

                            {/* Search bar */}
                            <label className={`input`}>
                                <input type="search" placeholder="Search" onChange={(e) => { filterUpdater("search")(e.target.value) }}></input>
                            </label>

                            {/* Elements filter */}
                            <div className="flex gap-2">
                                <div className={`flex items-center gap-2 h-[50px] overflow-auto`}>
                                    {
                                        Object.entries(elements).map(([key, value]) => (
                                            <button key={key} className={`flex-none p-0.5 hover:bg-neutral-500 hover:cursor-pointer rounded-md ${filters["element"].has(value as Element) ? "bg-accent" : ""}`} onClick={() => filterUpdater("element")(value)}>
                                                <img className="w-[30px] h-[30px]" src={`/Icon_Element_${value}.png`} />
                                            </button>
                                        ))
                                    }
                                </div>
                                <div className={`flex items-center`}>
                                    <ClearFilterButton onClick={filterClearer("element")} />
                                </div>
                            </div>


                            {/* Weapons filter */}
                            <div className="flex gap-2">
                                <div className="flex overflow-auto">
                                    <div className="flex-none grid grid-flow-row grid-rows-2 grid-cols-5 overflow-auto pb-2">
                                        {
                                            Object.entries(weapons).map(([key, value]) => (
                                                <button key={key} className={`p-0.5 hover:bg-neutral-500 hover:cursor-pointer rounded-md  ${filters["weapon"].has(value as Weapon) ? "bg-accent" : ""}`} onClick={() => filterUpdater("weapon")(value)}>
                                                    <img className="h-[20px]" src={`/Label_Weapon_${value}.png`} />
                                                </button>
                                            ))
                                        }
                                    </div>
                                </div>
                                <div className={`flex items-center pb-2`}>
                                    <ClearFilterButton onClick={filterClearer("weapon")} />
                                </div>
                            </div>


                            {/* Skill Group 1 Filters */}
                            <FilterGroup showSidebar={sidebarIsShown}
                                btnNames={SK1_NAMES}
                                groupName="Skill Group 1 Search"
                                currentFilters={filters["sk1Search"]}
                                selectedSkillsUpdater={filterUpdater("sk1Search")}
                                clearFilter={filterClearer("sk1Search")} />

                            {/* Skill Group 2 Filters */}
                            <FilterGroup showSidebar={sidebarIsShown}
                                btnNames={SK2_NAMES}
                                groupName="Skill Group 2 Search"
                                currentFilters={filters["sk2Search"]}
                                selectedSkillsUpdater={filterUpdater("sk2Search")}
                                clearFilter={filterClearer("sk2Search")} />

                            {/* Skill Group 3 Filters */}
                            <FilterGroup showSidebar={sidebarIsShown}
                                btnNames={SK3_NAMES}
                                groupName="Skill Group 3 Search"
                                currentFilters={filters["sk3Search"]}
                                selectedSkillsUpdater={filterUpdater("sk3Search")}
                                clearFilter={filterClearer("sk2Search")} />
                        </div>

                    </div>
                </Panel>
                <Separator>
                    <div className="w-0.5 h-full ml-1 mr-1 shrink-0 bg-gray-600" />
                </Separator>
                <Panel className="bg-base-300 p-2">
                    <ArtifactsList artifacts={artifacts} filterOpts={filters} />
                </Panel>
            </Group>
        </div>

    )
}
