// app/viewer/components/FilterGroupButton.tsx
import { MouseEventHandler } from "react"

type Props = {
    children: React.ReactNode
    className: string | undefined,
    onClick: MouseEventHandler<HTMLButtonElement> | undefined
}

export default function FilterGroupButton({ children, className, onClick }: Props) {
    return (
        <button className={`hover:bg-neutral-500 hover:cursor-pointer pl-2 pr-2 border rounded-md ${className}`} onClick={onClick}>
            {children}
        </button>
    )
}

// src/app/components/FilterGroupButton.vue
<script setup lang="tsx">
const props = defineProps<{
  readonly currentFilters: Set<string>;
  readonly btnName: string;
}>();

const emits = defineEmits<{
  updateFilter: [btnName: string];
}>();
</script>

<template>
  <button
    class="hover:bg-neutral-500 hover:cursor-pointer pl-2 pr-2 border rounded-md"
    :class="{ 'bg-accent text-base-200': currentFilters.has(btnName) }"
    @click="emits('updateFilter', btnName)"
  >
    {{ btnName }}
  </button>
</template>
